// <auto-generated />
using System;
using APICatalogo.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APICatalogo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211008124744_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("APICatalogo.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagemUrl = "http://www.example.com/imagens/1.jpg",
                            Nome = "Bebidas"
                        },
                        new
                        {
                            Id = 2,
                            ImagemUrl = "http://www.example.com/imagens/2.jpg",
                            Nome = "Lanches"
                        },
                        new
                        {
                            Id = 3,
                            ImagemUrl = "http://www.example.com/imagens/3.jpg",
                            Nome = "Sobremesas"
                        });
                });

            modelBuilder.Entity("APICatalogo.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<float>("Estoque")
                        .HasColumnType("REAL");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            DataCadastro = new DateTime(2021, 10, 8, 9, 47, 44, 127, DateTimeKind.Local).AddTicks(44),
                            Descricao = "Refrigerante de Cola",
                            Estoque = 50f,
                            ImagemUrl = "http://www.example.com/Imagens/coca.jpg",
                            Nome = "Coca-cola Diet",
                            Preco = 5.45m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            DataCadastro = new DateTime(2021, 10, 8, 9, 47, 44, 128, DateTimeKind.Local).AddTicks(3132),
                            Descricao = "Lanche de Atum com maionese",
                            Estoque = 10f,
                            ImagemUrl = "http://www.example.com/Imagens/atum.jpg",
                            Nome = "Lanche de Atum",
                            Preco = 8.50m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            DataCadastro = new DateTime(2021, 10, 8, 9, 47, 44, 128, DateTimeKind.Local).AddTicks(3152),
                            Descricao = "Pudim de leite condensado 100g",
                            Estoque = 20f,
                            ImagemUrl = "http://www.example.com/Imagens/pudim.jpg",
                            Nome = "Pudim 100g",
                            Preco = 6.75m
                        });
                });

            modelBuilder.Entity("APICatalogo.Models.Produto", b =>
                {
                    b.HasOne("APICatalogo.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("APICatalogo.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
